name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end/infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -input=false
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply --auto-approve

      - name: URL Capture
        id: capture
        run: |
          terraform output -raw api_url

      - name: URL Injection
        id: inject
        run: |
          sed -i "s#var apiUrl = \".*\"#var apiUrl = \"${{steps.tests.outputs.stdout }}\"#" "../../front-end/javascript/visitor-counter.js"
          echo "${{steps.capture.outputs.stdout}}"
#          chmod +x ../scripts/api-injection.sh
#          ../scripts/api-injection.sh "${{ steps.capture.outputs.stdout }}"

      # - name: Push Injection
      #   run: |
      #     git config --global user.email "billymm314@gmail.com"
      #     git config --global user.name "Billy Euceda"
      #     git commit -am "Auto Push"
